baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Hello, I'm Chris v1 test!"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Hello, I'm Chris!"
author = "Christopher Van Dusen"
copyright = "2020-2021"
description = "Wake up early. Drink Coffee. Work Hard. \n  \nDetroit, Michigan"
profilePicture = "images/profile.jpg"
keywords = "test"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/cvanduse/"

[[params.socialIcons]]
icon = "fab fa-facebook"
title = "facebook"
url = "https://www.facebook.com/cvanduse"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/fwd2cv/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:fwd2cv@gmail.com"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/FWD2CV"

[[params.socialIcons]]
icon = "fab fa-medium"
title = "medium"
url = "https://blog.fwd2cv.com"


<<<<<<< HEAD
<<<<<<< HEAD
[[params.socialIcons]]
icon = {{< button relref="/" [class="..."] >}}Get Home{{< /button >}}
{{< button href="https://github.com/alex-shpak/hugo-book" >}}Contribute{{< /button >}}
<<<<<<< HEAD
<<<<<<< HEAD
title = {{< button relref="/" [class="..."] >}}Get Home{{< /button >}}
{{< button href="https://github.com/alex-shpak/hugo-book" >}}Contribute{{< /button >}}
=======
title = medium
>>>>>>> parent of f21354e (Update config.toml)
=======
title = {{< button relref="/" [class="..."] >}}Get Home{{< /button >}}
{{< button href="https://github.com/alex-shpak/hugo-book" >}}Contribute{{< /button >}}
>>>>>>> parent of 49cda85 (Update config.toml)
url = "https://blog.fwd2cv.com"


=======
>>>>>>> parent of 235be66 (Update config.toml)
=======
>>>>>>> parent of 235be66 (Update config.toml)

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"
